id: P32935992
initial_creation_type: ocr
source_metadata:
  volumes:
    a7d606d2d9b447c0a131757d1371f8dc:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་དཀའ་འགྲེལ།
      total_pages: 1557
      volume_number: 62
